# makefile configuration
CPU	= msp430g2553
CFLAGS	= -mmcu=${CPU} -Os -I../h
LDFLAGS	= -L../lib -L/opt/ti/msp430_gcc/include/

# switches the compiler
CC	= msp430-elf-gcc
AS	= msp430-elf-gcc -mmcu=${CPU} -c

all: wakedemo.elf

# additional rules for files
wakedemo.elf: ${COMMON_OBJECTS} wakedemo.o buzzer.o wdt_handler.o
	${CC} ${CFLAGS} ${LDFLAGS} -o $@ $^ -lTimer -lLcd

load: wakedemo.elf
	msp430loader.sh $^

clean:
	rm -f *.o *.elf
	rm -f README.md~
	rm -f wakedemo.c~
	rm -f Makefile~
	rm -f buzzer.h~
	rm -f buzzer.c~

buzzer.c: buzzer.h
buzzerMain.c: buzzer.h
